name: Sofia-Env
channels:
    - nwani
    - defaults
dependencies:
    - defaults::python=3.6
    - nwani::portaudio
    - nwani::pyaudio
    - pip:
      - SpeechRecognition
      - gTTS
      - Pyttsx3
      - Pygame
      - Google
      - BeautifulSoup4
